version: '3.9'

services:
  webserver: # Apache webserver service
    container_name: belvedereapp
    build:
      context: . # Dockerfile path
      dockerfile: Dockerfile
    volumes: # Mount the local directory to /var/www/html in the container
      - ./app:/var/www/html       
    ports: # Map port on the host to port on the container 
      - 80:80
    environment:
      - DBHOST=db-belvedere-do-user-15912601-0.c.db.ondigitalocean.com
      - DBNAME=belvedere
      - DBUSERNAME=anonymous
      - DBPORT=25060
      - DBSSLMODE=require
      - DBPASSWORD=${DBPASSWORD}
