services:
  webserver: # Apache webserver service
    container_name: belvedereapp
    build:
      context: . # Dockerfile path
      dockerfile: Dockerfile
    ports: # Map port on the host to port on the container 
      - 80:80
    environment:
      - DBHOST=${DBHOST}
      - DBNAME=${DBNAME}
      - DBUSERNAME=${DBUSERNAME}
      - DBPORT=${DBPORT}
      - DBSSLMODE=${DBSSLMODE}
      - DBPASSWORD=${DBPASSWORD}